<a href="https://colab.research.google.com/github/garestrear/introduccion_ML_cursoUN/blob/main/Sesion1_IntroduccionPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Machine Learning* para aplicaciones en sistemas biológicos y Agronegocios**

# ¡¡Bienvenidos!!

En este curso esperamos enseñarte:

*  Nociones básicas e intermedias de Python. (1 sesión)
*  Manejo de bases de datos usando *Pandas*. (1 sesión)
*  Técnicas de graficación. (1 sesión)
*  *Machine learning* supervisado. (3 sesiones)
*  *Machine learning* no supervisado. (3 sesiones)
*  Ecuaciones estructurales. (3 sesiones)
*  Series de tiempo. (3 sesiones)

Para esto contamos con diferentes profesores capacitados para poderte acompañar en el aprendizaje.

Python y *Machine Learning* son temas amplios, con mucha documentación en la web y de gran aplicación a diversos problemas hoy en día.
Nuestro objetivo es acompañarlos en el proceso del aprendizaje: en cada sesión daremos nociones básicas de cada uno de los temas puesto que es imposible cubrir completamente un tema en tan poco tiempo.
Pero esperamos que, con lo visto en clase, trabajo autónomo y nuestra asesoría permanente, puedan avanzar en el aprendizaje del tema que más les interesa.

Esperamos que cada uno cuente con un conjunto de datos (tesis, proyecto de investigación) al que puedan aplicarle los conocimientos adquiridos a medida que sean vistos para que al final del curso nos puedan presentar el proyecto terminado.

Para lograr todo esto contamos con un canal de comunicación en **[Slack](https://join.slack.com/t/mlaplicensist-c9d9617/shared_invite/zt-p7qs69h1-0nMH93EfMEgCN9VLaXLauw)**
 al cual serán invitados mendiante el correo electrónico que nos proporcionaron.
Además aquí dejamos los correos electrónicos de cada uno de los profesores:

*  Anel Galaviz : anelglvz@gmail.com
*  Gustavo Restrepo : garestrear@unal.edu.co
* Guillermo Ramirez : jgramireg@unal.edu.co
* Mario Moctezuma: m.a.mocte@gmail.com
*  Max Mitre: maxmitre91@gmail.com
* Natalia Cadavid: ncadavia@unal.edu.co
* Sebastian Vélez: svelezv@unal.edu.co
* Wincy Guerra: waguerra@unal.edu.co
* Javier Moreno: javamo93@gmail.com

## **¿ Cómo se usa?**
Hay muchas formas de usar Python, debido a la cantidad de versiones, programas y páginas que te permiten editar y ejecutar comandos del lenguaje.

Por ejemplo:
* Con esta herramienta de Google llamada **Colab o Colaboratory**, puedes usar Python en línea y correr tus códigos en servidores de Google.C.
* Puedes descargar "ANACONDA", la distribución de Python más popular en el mundo (https://www.anaconda.com/products/individual), en tu PC, la cual trae otros sofwares de interés en la computación científica como R.
* Puedes usar "la ventanita negra" (command prompt) de tu computador para instalar un compilador de Python y trabajar desde ahí. Si usas linux o MAC es posible que ya tengas Python. Por supuesto también puede instalarse un editor de código adicional para que se vea mejor. 

Por ahora estamos locos por empezar a programar así que no hablaremos más del tema y seguiremos en Colab.

>### Más sobre Colab
Desde tu google Drive, le das en "Nuevo", luego le das en "mas opciones" y luego búscas la opción "Google Colaboratory". Después de que se abra el archivo las cosas están listas para que te conviertas en programador(a).
Un Colab se divide en cajones celdas, hay celdas para escribir texto, como esta en la que estás leyendo y hay celdas para escribir códigos como las que verás mas abajo. 

# **Nociones preliminares.**


Empezamos haciendo unas pequeñas definiciones y viendo cómo funciona cada uno de los objetivos definidos.

## **1. print()**
Esta es la función que usaremos para imprimir o mostrar algo en la pantalla del usuario.
Para entenderlo mejor ejecutaremos los siguientes códigos:
* 
```
print("Hola mundo!")
```


* ``` 
print("Aprenderemos Python")
```
* ```
print(3+5)
```
* 
``` 
print(5+2==7)
```

In [ ]:
##***************************************************** Tu turno ***************************************************** ##
# Escribe comandos similares a los de arriba y ejecuta la celda dando click en la flechita de la izquierda o presionando ctrl+Intro.
print("lo que se nos ocurra")
print(3+6)
print(5+3==8)

lo que se nos ocurra
9
True


# **2. Variables**
Es el sitio donde guardamos cierto dato. Por ejemplo
```x=3```
significa que vamos a guardar el número $3$ en la variable $x$.

**Tu turno**: Asignemos a la variable ```Python``` el valor ```'me gusta'```.

**Tu turno**: Hagamos ahora ```x=6``` y ```z=44```.

**Tu turno**: ¿Qué valor tiene la variable ```desconocido = x+z```?

In [ ]:
##***************************************************** Tu turno ***************************************************** ##
# Completa las instrucciones reemplazando la raya por el valor adecuado
Python = "otro valor"
z = 6
x=44
desconocido = x+z
Hoy = True


In [ ]:
print(Hoy)

True


In [ ]:
desconocido

50

# **3. Tipos de datos.**
Hay varios tipos de datos:
* **Int:** números enteros como $0$, $-34$, $26$.
* **Float:** son los números reales, es decir, los números enteros junto con los números decimales: $2/3$, $-9.45$, $5.0$
* **Booleanos:** son solo dos valores: Verdadero o Falso, pero siempre los escribiremos en inglés: $True$ y $False$ (a veces se entienden como 1 y 0 -por ejemplo, intenta ejecutar $True + True$). Hay que tener cuidado de escribirlos siempre con la primera letra mayúscula.
* **String:** es decir, cadenas. Son los datos que expresamos colocándolos siempre entre comillas "string" o 'string'. Aquí podemos usar letras, números o símbolos. Por ejemplo: "Jorge", "cinco", "Python3.1", "Aprenderemos mucho!!", "5".

## ¿Cómo convertir un dato de un tipo a otro?

Para saber de qué tipo es un dato usamos la función ```type()```.

Y para cambiar el tipo de un dato usamos las funciones ```int()```, ```str()```, ```float()``` y ```bool()```.

In [ ]:
entero = -56
decimal = 4.56
cadenas = "mi nombre"
booleano = True

print(type(cadenas))

print(bool(0))

print(int(decimal))

print(str(decimal))

print(float(entero))

<class 'str'>
False
4
4.56
-56.0


In [ ]:
print(type(str(decimal)))

<class 'str'>



# **4. Listas**
Una lista es una sucesión de datos ordenados. Las listas se ordenan desde la posición $0$ en adelante. Por ejemplo:
```
[5,-3,'jorge',34, True]
```
es una lista con $5$ datos. Note que el dato $5$ está en la posición $0$ y el dato "jorge" está en la posición $2$.

Asignemos a la variable *prueba* la lista anterior:
```
prueba = [5,-3,'jorge',34, True]
```

Para acceder a un dato de una lista usamos el nombre de la lista o la variable a la que fue asignada (en este caso *prueba*) junto con la posición del dato al que queremos acceder. Por ejemplo, si queremos acceder al dato $34$ que está en la posición (**Tu turno**?) escribimos:
```
prueba[3]
```
Para ver el resultado escribimos ```print(prueba[3])```.

In [ ]:
##***************************************************** Tu turno ***************************************************** ##
# Crea la lista
prueba = [5,-3, "jorge", 34, True, 34] # estoy definiendo un arreglo
# Accede al dato 'jorge'.
print(prueba[3])
# Accede al último dato.
print(prueba[5])
#print(prueba)
print(prueba.index(34))

34
34
3


## **Sublistas**

No siempre queremos la lista completa. Python nos permite tomar la sublista que deseemos mediante la notación ```lista[a:b]```. En este caso Python crea una nueva lista que consta del elemento ubicado en la posición *a* hasta el elemento que está **antes de la posición *b***.

In [ ]:
lista = [0,1,2,3,4,5,6,7,8,9,10,11]


In [ ]:
lista_5_9 = lista[5:10]
lista_5_9

[5, 6, 7, 8, 9]

## ¿Y si solo quiero el elemento 1, 3 y 7?

Para esto usamos la función ```lista.append(nuevo elemento)```.

Creamos una lista vacía ```lista_1_3_7=[]``` y usamos la función append para agregar los elementos que deseemos.

In [ ]:
lista_1_3_7=[]
lista_1_3_7

[]

In [ ]:
lista_1_3_7.append(lista[1])
lista_1_3_7.append(lista[7])
lista_1_3_7.append(lista[3])
lista_1_3_7

[1, 7, 3, 1, 7, 3]

In [ ]:
lista_1_3_7.remove(7)

In [ ]:
lista_1_3_7.remove(7)
lista_1_3_7

[1, 3, 1, 3]

## ¿Cómo ordenar una lista?

Python cuenta con el comando ```lista.sort(reverse = False)```.
El parámetro reverse le indica a la función si quiere que se ordene la lista de mayor a menor.

In [ ]:
#Intenta ordenar la lista lista_1_3_7 de mayor a menor
lista_1_3_7.sort(reverse = True)

In [ ]:
print(lista_1_3_7)

[7, 3, 1]

Para más información sobre listas, puedes consultar [aquí](https://www.w3schools.com/python/python_lists_methods.asp).

## **5. len() y range()**
Debes conocer estas funciones porque serán muy útiles a lo largo de este curso. Vamos a intentar descubrir por nosotros mismos para qué son.
Primero definamos la siguiente lista:
```
 lista = [5,-3,'jorge',34, True]
 ```


* **¿Qué pasa si hacemos  ```len(lista)```?**

In [ ]:
##***************************************************** Tu turno ***************************************************** ##
# Escribe la instrucción, ejecútala y comenta en frente qué crees que significa. 
lista = [5,-3,'jorge',34, True]
print(len(lista))

5


La función **range(n)** te ayuda a generar rápidamente un conjunto de números que empiezan en cero y terminan justo antes de n con incrementos de uno en uno.
Por ejemplo, range(5) hace que python internamente genere los números [0,1,2,3,4]. Python no los muestra aunque uses print(range(5)) pero ahí están.


* **¿Qué pasa si hacemos  ```range(7)```?**

* **¿Qué pasa si hacemos  ```range(len(lista))```?**

In [ ]:
##***************************************************** Tu turno ***************************************************** ##
# Escribe los comandos, ejecuta y responde las dos preguntas anteriores. 
print(range(7))
print(range(len(lista)))

range(0, 7)
range(0, 5)


*Nota:* En algunas versiones de Python siempre es necesario usar el comando print( ) para poder ver los resultados. En Colab no es necesario aunque sólo se te imprime el último resultado.

**En resumen:**
* La función ```len(lista)``` calcula la longitud de una lista dada.
*La función ```range(n)``` genera una lista con los primeros $n$ números enteros empezando desde cero (es decir que va desde $0$ hasta $n-1$). En realidad esta función es un iterador.

In [ ]:
##***************************************************** Tu turno ***************************************************** ##
# Ejecuta las siguientes instrucciones y explica los resultados obtenidos
print(4 in range(5))
# 
print(3.5 in range(5))
#

True
False


# **6. ¿Para qué las funciones range() y len()?**
## Loops.

Vamos a crear un arreglo con los nombres de los profesores:
```
profesores = ["anel", "natalia", "wincy", "gustavo", "guillermo", "sebastian", "javier", "max", "mario"]
```
Y queremos asignarle una calificación por la calidad de su clase: para esto creamos otro arreglo que se llame calificación
```
calificación = [? , ? , ? , ?, ?, ?, ?, ?, ?]
```

Podemos asignar la calificiación 1 por 1 o podemos crear un ```for```que nos permita hacer esto automáticamente.

**Nota: aquí parece mejor opción hacerlo 1 a 1, pero en un conjunto de datos con 2.000 entradas parecerá mejor hacer un loop.**

# ¿Cómo es la estructura de un ```for```?

```
for (iterante) in (iterable):
    (accion que queremos que se repita tantas veces como el iterador diga)

#Aquí continua el código que va fuera del for
```

**Precaución: no olvidar los dos puntos (:)**


In [ ]:
profesores = ["anel", "natalia", "wincy", "gustavo", "guillermo", "sebastian", "javier", "max", "mario"]

In [ ]:
for i in range(len(profesores)):
  print(i)
  print(i+8)
  suma = i
  print("Esto está fuera del for")
print(suma)

0
8
Esto está fuera del for
1
9
Esto está fuera del for
2
10
Esto está fuera del for
3
11
Esto está fuera del for
4
12
Esto está fuera del for
5
13
Esto está fuera del for
6
14
Esto está fuera del for
7
15
Esto está fuera del for
8
16
Esto está fuera del for
8


In [ ]:
for profesor in profesores:
  print(profesor)

anel
natalia
wincy
gustavo
guillermo
sebastian
javier
max
mario


In [ ]:
profesores

['anel',
 'natalia',
 'wincy',
 'gustavo',
 'guillermo',
 'sebastian',
 'javier',
 'max',
 'mario']

In [ ]:
notas=[]
for profesor in profesores:
  notas.append(len(profesor))

print("Las notas de los profesores son", notas)

Las notas de los profesores son [4, 7, 5, 7, 9, 9, 6, 3, 5]


In [ ]:
promedio = 0
for x in notas:
  promedio = promedio + x

resultado = promedio / len(notas)
print(resultado)


6.111111111111111


In [ ]:
for i in range(len(notas)):
  print("La nota del profesor", profesores[i], "es", notas[i])
  

La nota del profesor anel es 4
La nota del profesor natalia es 7
La nota del profesor wincy es 5
La nota del profesor gustavo es 7
La nota del profesor guillermo es 9
La nota del profesor sebastian es 9
La nota del profesor javier es 6
La nota del profesor max es 3
La nota del profesor mario es 5


In [ ]:
Todo=[]
for i in range(len(notas)):
  if notas[i]>=7:
    print("Profesor ", profesores[i], " aprobo con ", notas[i])
    Todo.append([notas[i],profesores[i]])
  else:
    print("Profesor ", profesores[i], " no aprobo con ", notas[i])
    Todo.append([notas[i],profesores[i]])
Todo.sort()

Profesor  anel  no aprobo con  3
Profesor  natalia  no aprobo con  4
Profesor  wincy  no aprobo con  5
Profesor  gustavo  no aprobo con  5
Profesor  guillermo  no aprobo con  6
Profesor  sebastian  aprobo con  7
Profesor  javier  aprobo con  7
Profesor  max  aprobo con  9
Profesor  mario  aprobo con  9


[[3, 'anel'],
 [4, 'natalia'],
 [5, 'wincy'],
 [5, 'gustavo'],
 [6, 'guillermo'],
 [7, 'sebastian'],
 [7, 'javier'],
 [9, 'max'],
 [9, 'mario']]

In [ ]:
Todo.sort()
Todo

[[3, 'anel'],
 [4, 'natalia'],
 [5, 'gustavo'],
 [5, 'wincy'],
 [6, 'guillermo'],
 [7, 'javier'],
 [7, 'sebastian'],
 [9, 'mario'],
 [9, 'max']]

In [ ]:
for i in Todo:
  if i[0]>=7:
    print("El profesor ", i[1], "aprobo con ", i[0])
  else:
    print("El profesor ", i[1], "no aprobo con", i[0])

El profesor  3 no aprobo con anel
El profesor  4 no aprobo con natalia
El profesor  5 no aprobo con gustavo
El profesor  5 no aprobo con wincy
El profesor  6 no aprobo con guillermo
El profesor  javier aprobo con  7
El profesor  sebastian aprobo con  7
El profesor  mario aprobo con  9
El profesor  max aprobo con  9


In [ ]:
lista = [x for x in range(7)]
lista

[0, 1, 2, 3, 4, 5, 6]

Note que cuando el profesor es una mujer, nuestro código escribe *profesor* en vez de *profesora*. Para solucionar esto podemos usar un *if*

# **7. Condicionales: if, else.**

Un condicional nos permite activar o no cierta porción de nuestro código siempre que se cumpla o incumpla una condición dada.

Por ejemplo:
```
if (condicion)==True/False:
  #realiza la porción de código
  # que pongamos en estas líneas.

else:
  #si no se cumple la condición
  #ejecuta esta otra porcion.
```

**Nota: no es necesario poner el ```else``` siempre. Se pueden poner varios ```if``` seguidos.**
**Precaución: no olvidar los dos puntos (:)**

In [ ]:
for i in range(len(notas)):
  if profesores[i] in ["natalia", "anel"]:
    print("La nota de la profesora", i, "es", notas[i])
  else:
    print("La nota del profesor", profesores[i], "es", notas[i])

La nota de la profesora 0 es 4
La nota de la profesora 1 es 7
La nota del profesor wincy es 5
La nota del profesor gustavo es 7
La nota del profesor guillermo es 9
La nota del profesor sebastian es 9
La nota del profesor javier es 6
La nota del profesor max es 3
La nota del profesor mario es 5


# ¿Cuáles profesores aprobaron, teniendo en cuenta que se aprueba con 7 o más?

In [ ]:
## Inténtalo!
for i in range(len(profesores)):
  if notas[i]>=7:
    print(profesores[i])


natalia
gustavo
guillermo
sebastian


Los loops y los condicionales nos ayudan a filtrar la información de nuestro conjunto de datos. Esto es útil para clasificar, cambiar o identificar factores que nos permitan hacer un mejor análisis de nuestros datos.

# **8. Diccionarios**

Los diccionarios son usados para guardar información. Para ellos usamos una llave (*key*) y a cada llave le asignamos un valor.
Tal valor puede ser un arreglo, una cadena, otro diccionario...

```
diccionario ={ llave1 : valor1, llave2 : valor2, ...}
```
Para acceder a cada valor usamos la misma notación que en los arreglos solo que en vez de usar el índice, usamos la llave.
```
diccionario[llave1]
``` 

**Precaución:** las llaves no pueden estar repetidas.

In [ ]:
Datos_personales = {"direccion" : "calle 25 # 72a-48", "edad" : 27, "correo" : "javamo93@gmail.com", "calificaciones" : [2,4,5,2,2,5]}

In [ ]:
Datos_personales["direccion"]

'calle 25 # 72a-48'

In [ ]:
Datos_personales["calificaciones"]

[2, 4, 5, 2, 2, 5]

In [ ]:
Datos_personales["calificaciones"][3]

2

## Para agregar un nuevo item al diccionario:

Es sencillo: usamos la nueva llave y le asignamos el nuevo valor:
```
diccionario["nueva llave"] = nuevo valor (arreglo, diccionario, cadena, número...)
```

In [ ]:
#Agrégale algo nuevo al diccionario Datos_personales
Datos_personales["  "]=??

In [ ]:
Datos_personales

Sobre los diccionarios también podemos iterar

In [ ]:
for key in Datos_personales:
  print(key)

direccion
edad
correo
calificaciones


In [ ]:
for key in Datos_personales:
  print(Datos_personales[key])

calle 25 # 72a-48
27
javamo93@gmail.com
[2, 4, 5, 2, 2, 5]


Para más información sobre diccionarios puedes consultar [aquí](https://www.w3schools.com/python/python_dictionaries_methods.asp).

# **9. Funciones lambda y map**

Supongamos que tenemos el siguiente problema:

Tenemos un arreglo con los salarios de todos los empleaños de una compañía y somos los encargados de actualizar el salario gracias a un aumento del 16% que hubo para todos los trabajares de la compañía.

La compañía tiene 2367 trabajadores. ¿Qué hacer?

**Respuesta:** 
* Un for.
*  Una función.
*  Un mapeo.

In [ ]:
salarios = [100, 387, 56, 190, 280, 1290, 289, 54, 634, 235, 274, 234, 642, 237, 237, 12, 0, 78594, 235, 938]

In [ ]:
#Solución 1


## **Lambda función**

Las funciones lambda son funciones *anónimas* que solo pueden tener cualquier número de argumentos pero solo una expresión

![image.png](https://i1.faceprep.in/Companies-1/python-lambda-functions-new.png)

*Imagen tomada de https://i1.faceprep.in/Companies-1/python-lambda-functions-new.png


Vamos a crear una función lambda que tome una variable x y me devuelva x por 1.16

In [ ]:
aumento = lambda x: 1.16*x

aumento(100)

115.99999999999999

In [ ]:
# Solucion 2 usando un for y una lambda función

## **Función Map**

La función toma como argumento una función y un iterador y retornar otro iterador.

``` map(funcion, iterador)```

Este iterador que retorna se puede convertir a una lista usando el comando ```list()```.

In [ ]:
nuevos_salarios = map(aumento, salarios)
print(nuevos_salarios)

In [ ]:
nuevos_salarios = list(nuevos_salarios)
print(list(nuevos_salarios))

[115.99999999999999, 448.91999999999996, 64.96, 220.39999999999998, 324.79999999999995, 1496.3999999999999, 335.23999999999995, 62.63999999999999, 735.4399999999999, 272.59999999999997, 317.84, 271.44, 744.7199999999999, 274.91999999999996, 274.91999999999996, 13.919999999999998, 0.0, 91169.04, 272.59999999999997, 1088.08]


## **¿Cuánto fue el aumento de cada salario?**

¿Lo puedes hacer en una sola línea?

Ayuda: usar una nueva función lambda que 

In [ ]:
print(list(map(lambda x,y: y-x, salarios, nuevos_salarios)))

[15.999999999999986, 61.91999999999996, 8.959999999999994, 30.399999999999977, 44.799999999999955, 206.39999999999986, 46.23999999999995, 8.639999999999993, 101.43999999999994, 37.599999999999966, 43.839999999999975, 37.44, 102.71999999999991, 37.91999999999996, 37.91999999999996, 1.9199999999999982, 0.0, 12575.039999999994, 37.599999999999966, 150.07999999999993]


# **10. Numpy**

Esta librería convertirá a Python en "Una súper calculadora".

---



Una librería es un conjunto de funciones y métodos que ya están predefinidas y nos ayudarán a hacer los cálculos de forma más sencilla.


Empezamos cargando la librería, es decir, dándole a Python el poder de usar estas funciones. Para esto utilizamos el comando **import** y agregamos el nombre de la librería que queremos, que en este caso es **numpy**

```import numpy as np```



In [ ]:
import numpy as np


Siempre que carguemos una libreria podemos ponerle un *alias* que nos permitirá usarlas de forma abreviada. 

En el caso de Numpy usamos el *alias* de *np*. Esto es una convención que se usa entre la mayoría de programadores de Python.

Otra librería que usaremos en la próxima sesión será la de ***pandas***. A esta libería se le suele asignar el *alias* *pd*

```import pandas as pd```

## **Instalar paquetes.**

Para instalar un paquete con el que Colab no cuente, usamos la línea de código
```
!pip install (paquete)
```
Por ejemplo, si queremos instalar el paquete *tensorflow* hacemos lo siguiente:

In [ ]:
!pip install tensorflow

## **Funciones aplicadas a arreglos Numpy** 
Numpy tiene la gran ventaja de que podemos usar un arreglo hecho con numpy para hacer el cálculo de forma más sencilla. 

Para esto usaremos el comando ```np.array([aqui ponemos el array])```. Repitamos los calculos de la actualización de salario usando un arreglo de numpy.

In [ ]:
salarios_numpy = np.array(salarios)
salarios_numpy

array([  100,   387,    56,   190,   280,  1290,   289,    54,   634,
         235,   274,   234,   642,   237,   237,    12,     0, 78594,
         235,   938])

In [ ]:
salarios

[100,
 387,
 56,
 190,
 280,
 1290,
 289,
 54,
 634,
 235,
 274,
 234,
 642,
 237,
 237,
 12,
 0,
 78594,
 235,
 938]

Como queremos multiplicar cada entrada por 1.16, tomamos el arreglo en numpy y lo multiplicamos por 1.16. (Sí, así de fácil!)

En general será
```
arreglo_nuevo = arreglo_numpy * (funcion que se le quiere aplicar a cada entrada)
```

In [ ]:
salario_actualizado_numpy = salarios_numpy *1.16
salario_actualizado_numpy

array([1.160000e+02, 4.489200e+02, 6.496000e+01, 2.204000e+02,
       3.248000e+02, 1.496400e+03, 3.352400e+02, 6.264000e+01,
       7.354400e+02, 2.726000e+02, 3.178400e+02, 2.714400e+02,
       7.447200e+02, 2.749200e+02, 2.749200e+02, 1.392000e+01,
       0.000000e+00, 9.116904e+04, 2.726000e+02, 1.088080e+03])

Otros ejemplos:

In [ ]:
arreglo_aleatorio = np.random.rand(4) #genera un arreglo de 4 elementos con números aleatorios entre 0 y 1.
arreglo_aleatorio

array([0.11303702, 0.11846482, 0.61277561, 0.33765272])

In [ ]:
arreglo_aleatorio = np.random.rand(4)*100 #genera un arreglo de 4 elementos con números aleatorios entre 0 y 100.
arreglo_aleatorio

array([84.29863987,  9.03859201, 58.08715996, 30.19460566])

In [ ]:
seno_de = np.sin(arreglo_aleatorio) #aplica la función seno a cada entrada del arreglo.
seno_de

array([ 0.50066063,  0.37665801,  0.99947827, -0.93955245])

In [ ]:
raiz_cuadrada = np.sqrt(arreglo_aleatorio)#aplia la raíz cuadrada a cada entrada del arreglo.
raiz_cuadrada

array([9.18142908, 3.00642512, 7.62149329, 5.49496184])

In [ ]:
cambio_salario = salario_actualizado_numpy - salarios_numpy
cambio_salario

array([1.600000e+01, 6.192000e+01, 8.960000e+00, 3.040000e+01,
       4.480000e+01, 2.064000e+02, 4.624000e+01, 8.640000e+00,
       1.014400e+02, 3.760000e+01, 4.384000e+01, 3.744000e+01,
       1.027200e+02, 3.792000e+01, 3.792000e+01, 1.920000e+00,
       0.000000e+00, 1.257504e+04, 3.760000e+01, 1.500800e+02])

In [ ]:
arreglo_enteros = np.random.randint(3, 17, 5)#genera un arreglo de números enteros desde el 3 hasta el 17 con 5 entradas.
arreglo_enteros

array([14,  3,  4,  9,  9])

Las capacidades que tiene Numpy son enormes. Te invitamos a que consultes más en la web. [Aquí](https://damianavila.github.io/Python-Cientifico-HCC/3_NumPy.html) te dejamos un inicio para que puedas ver operaciones de álgebra lineal y otras operaciones que tiene Numpy.